version: '3.8'

services:

  sender:
    build: 
      context: ./sender
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./sender:/app
    depends_on:
      - receiver

  receiver:
    build: 
      context: ./receiver
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./receiver:/app